# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Github needs
safe: true
lsi: false

# Site settings
title: Max Halldén
description: > # this means to ignore newlines until "baseurl:"
  Personal page of Max Halldén, software developer and Linux nerd.
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://maxhallden.com" # the base hostname & protocol for your site
twitter_username: halldenMax     
github_username: maxha651 

# Build settings
markdown: kramdown

timezone: Europe/Stockholm

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      author: "Max Halldén"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "default"
      author: "Max Halldén"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      author: "Max Halldén"



